### ISSUE TITLE
Mobile Example

### ISSUE THREAD

**Issue by Nazariglez** [goxjs/example#1]
Hi!

Thank you so much for this awesome package. I'm thinking of using it to build a cross-platform 2d game framework, is it possible to add a small guide of how to build a mobile app? I can build without any problem the examples for desktop and gopherjs, but when i try to use gomobile fails.

I know, this examples need more work (and dependencies) to use with gomobile, but I'm not sure where I can start. Thanks

**Comment by dmitshur** [comment]
Hi @Nazariglez.

I'm glad you like it!

Currently, the two goxjs packages (gl and glfw) work in tandem to support OpenGL/OpenGL ES/WebGL applications on desktop OSes (macOS, Linux, and Windows) and inside browsers.

However, only the gl package has support for mobile devices (iOS and Android), the glfw package does not. The gl package is not directly compatible with gomobile. Adding support for mobile OSes to glfw is possible, but non-trivial and quite a bit of work, and future maintenance. I don't have short term plans to work on that myself.

Hope that answers your question, and let me know if you have other questions or if you're interested in learning any more details about the current status. Thanks!

**Comment by Nazariglez** [comment]
Yes, that answers my question, thanks!

I'm new in "go-land" just a few months, by now I will "play" a bit with this packages and the official mobile examples, and maybe in a near future I can do myself a simple wrapper to use a glfw -like API in mobile too.

I really appreciate your help, thanks

**Comment by Bluebugs** [comment]
Hi, sorry to resurrect this issue, but I am quite interested to use goxjs/gl and goxjs/glfw as an abstraction layer for a UI toolkit (fyne.io). What would be an acceptable path/way to get Android and iOS support working in your opinion?

**Comment by dmitshur** [comment]
Hi @Bluebugs,

What I wrote above in https://github.com/goxjs/example/issues/1#issuecomment-263730520 is still true. Adding mobile Android/iOS support would requiring porting much of internal code available in the golang.org/x/mobile subrepository and adapting it to fit the GLFW-style API that goxjs/glfw uses. I don't think it'll be possible to use the public APIs available in golang.org/x/mobile directly to accomplish this task efficiently. That's why it's quite hard and a large volume of work.

**Comment by Bluebugs** [comment]
I also realize that the mobile keyboard is not going to fit well with glfw API. Might be best to use golang.org/x/mobile directly for us.
